/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flyscale_chapter_4_OpenSLESSoundPlayer */

#ifndef _Included_com_flyscale_chapter_4_OpenSLESSoundPlayer
#define _Included_com_flyscale_chapter_4_OpenSLESSoundPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flyscale_chapter_4_OpenSLESSoundPlayer
 * Method:    getStringFromJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_chapter_14_OpenSLESSoundPlayer_getStringFromJNI
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_flyscale_chapter_4_OpenSLESSoundPlayer
 * Method:    setAudioDataSource
 * Signature: (Ljava/lang/String;F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_flyscale_chapter_14_OpenSLESSoundPlayer_setAudioDataSource
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_flyscale_chapter_4_OpenSLESSoundPlayer
 * Method:    getAccompanySampleRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_flyscale_chapter_14_OpenSLESSoundPlayer_getAccompanySampleRate
  (JNIEnv *, jobject);

/*
 * Class:     com_flyscale_chapter_4_OpenSLESSoundPlayer
 * Method:    Play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flyscale_chapter_14_OpenSLESSoundPlayer_play
  (JNIEnv *, jobject);

/*
 * Class:     com_flyscale_chapter_4_OpenSLESSoundPlayer
 * Method:    getCurrentTimeMills
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_flyscale_chapter_14_OpenSLESSoundPlayer_getCurrentTimeMills
  (JNIEnv *, jobject);

/*
 * Class:     com_flyscale_chapter_4_OpenSLESSoundPlayer
 * Method:    Stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_flyscale_chapter_14_OpenSLESSoundPlayer_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
